data-dir: /Users/heades/teaching/HCI/website

from: markdown+emoji

to: html

template: layouts/site

output-file: 

input-files: []

standalone: true

self-contained: false

table-of-contents: true
toc-depth: 3
number-sections: false

highlight-style: pygments

email-obfuscation: javascript
metadata:
  email: heades@augusta.edu

html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"

css:
- "/hciweb/includes/css/default.css"
